<?php
/**
 * Created by PhpStorm.
 * User: huangxr
 * date: 2015/12/3
 * Time: 10:00
 */

/**
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

1: 1
3: 1,3
6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
 */
$result = 0;
for($i = 1; $i <= 20000; $i++){
    $result = getSum($i);
    $divisorsNum = 0; //有多少个因子
    $sqrt = sqrt($result);
    if(is_int($sqrt)){
        $divisorsNum += 1;
    }else{
        $sqrt = intval($sqrt);
    }
    for($j = 1; $j < $sqrt; $j++){
        if($result % $j == 0){
            $divisorsNum += 2;
        }
    }
    if($divisorsNum >= 500){
        echo $result;
        break;
    }
}

function getSum($num)
{
    if($num % 2 == 0){
        $sum = (1 + $num) * ($num / 2);
    }else{
        $prev = $num - 1;
        $sum = (1 + $prev) * ($prev / 2) + $num;
    }
    return $sum;
}

